name: Node.js CI CD

on:
  push:
    branches: [ master ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '17.x'
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test
#   deploy-staging:
#     needs: build
#     environment: staging
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: akhileshns/heroku-deploy@v3.12.12
#         with:
#           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#           heroku_app_name: "test-node-server-staging"
#           heroku_email: "ganeshrockz@github.com"
#   trigger_e2e_tests:
#     needs: deploy-staging
#     runs-on: ubuntu-latest
#     steps:
#       - name: Pull E2E tests suite
#         run: |
#           cd ../
#           git clone https://github.com/ganes-constellation/e2e-test-suite
#           cd e2e-test-suite/
#           git init
#           cd deployments/
#           echo "DEPLOYMENT TRIGGERED IN ${GITHUB_REPOSITORY} FOR ${GITHUB_SHA}" >> deployment.txt
#           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
#           git config --global user.name "github-actions[bot]"
#           git commit -m "Deployment changes" -a
#           git remote remove origin
#           git remote add origin https://${{secrets.REPO_PUSH_TOKEN}}@github.com/ganes-constellation/e2e-test-suite.git
#           git push origin master
#   deploy-production:
#     needs: deploy-staging
#     environment: production
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: akhileshns/heroku-deploy@v3.12.12
#         with:
#           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#           heroku_app_name: "test-node-server"
#           heroku_email: "ganeshrockz@github.com"
